### ISSUE TITLE
Recommend using reprepo -b to add packages

### ISSUE THREAD

**Issue by jbdatko** [adafruit/Adafruit-Occidentalis#1]
Just leaving a drive by comment. I noticed you are using [dpkg-sig](https://github.com/adafruit/Adafruit-Occidentalis/blob/master/repo/deploy.sh#L55) and there's a big warning on the Debian [wiki](https://wiki.debian.org/SettingUpSignedAptRepositoryWithReprepro#Signing_Debian_packages_without_adding_to_repository) to not do that.

I'm not claiming to be an apt-expert, but I think the following is recommended:

```
reprepro -b /var/repositories includedeb trusty example-helloworld_1.0.0.0_*
```

I found that tidbit from [Digital Ocean's](https://www.digitalocean.com/community/tutorials/how-to-use-reprepro-for-a-secure-package-repository-on-ubuntu-14-04) guide. 

Otherwise, I think it's great to host this stuff in an apt server!

**Comment by brennen** [comment]
Thanks - will sort!

**Comment by brennen** [comment]
Closing, as we're no longer maintaining this packageset or the apt repo.
