### ISSUE TITLE
unmet dependencies in adafruit-io-gif Package

### ISSUE THREAD

**Issue by carriere4** [adafruit/Adafruit-Occidentalis#13]
got this error when trying to install the adafruit-io-gif Package

The following packages have unmet dependencies:
 adafruit-io-gif : Depends: node (>= 0.12.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by vlasse86** [comment]
You need to install Node.js first:
`apt-get install node`
