### ISSUE TITLE
Problem with authentication of repository

### ISSUE THREAD

**Issue by microniko** [adafruit/Adafruit-Occidentalis#15]
After an `apt update`, I add this error :

> W: Erreur de GPG : http://apt.adafruit.com/raspbian wheezy InRelease : Les signatures suivantes ne sont pas valables : 58A1FE78D61C7C13E28B92A7C24E6D5378661FA5
> W: The repository 'http://apt.adafruit.com/raspbian wheezy InRelease' is not signed.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

I'm with Raspbian Stretch

Thx

**Comment by brennen** [comment]
Closing, as we've permanently deactivated `apt.adafruit.com`.
