### ISSUE TITLE
Rename PiTFT Kernel Package

### ISSUE THREAD

**Issue by toddtreece** [adafruit/Adafruit-Occidentalis#3]
The PiTFT kernel will install if the user runs `apt-get upgrade` after adding the repo. Rename the PiTFT kernel to avoid this issue.

**Comment by brennen** [comment]
Oh dang.  I definitely should have given this more thought.

**Comment by toddtreece** [comment]
@brennen me too. I added a warning to the guide until we can rename it.

**Comment by ladyada** [comment]
if this requires a repackage, plz hold for a couple days: @microbuilder has a few requests for extra kernel modules to turn on in the pi kernel for 6lopan support, so we can do both at once?

**Comment by toddtreece** [comment]
@ladyada sounds good. I'll add the rename modifications to the PiTFT branch in the Kernel-o-Matic repo on Monday and we can repackage once we have the new modules figured out.

**Comment by monroerl** [comment]
Does this mean we can finally get rid of this ugly thing "Please note, we are still working on Pi 2 support for this screen!" at https://www.adafruit.com/product/1601 ? That would be great because I'm giving a big class in July and I hate to stick with the B+ if screens don't work for Pi2. Thanks

**Comment by ladyada** [comment]
@monroerl  Yes the tutorial is updated for that one, the others are coming soon. its unrelated to this issue which is about package names

**Comment by monroerl** [comment]
Thank you. Now I just need Kali to update to support the screen. I'm giving
a large class on using the Pi as a pent test and forensic tool. I was
thinking about having the class outside to show off the portability of the
Pi using Anker chargers, TFT screens, WiFi dongles and Bluetooth keyboards.
I don't think the convention will allow me to move the whole class outdoors
but it's worth a try. I'll be ordering at least a dozen of each, maybe
twenty to thirty depending on how many people are willing to learn and
shell out the money.

I appreciate and admire your work. Keep it up,
Bob Monroe

**Comment by combs** [comment]
still a problem?

**Comment by monroerl** [comment]
I submitted a support request into the folks at Kali about adding TFT to
their next image for the Pi 2. I have discovered an issue with Windows 8.1
not playing well with microSD cards. My other laptop wasn't making proper
images and that frustrated the hell out of me. I found out from other
bloggers that there is a problem with Windows 8.1 not being able to create
bootable images in Win32DiskImager. That gave me a couple of heart attacks
when I've got RSA coming up in two weeks. I need my microcomputers to work
for the classes I'm giving. So now I'm making all build on other computers.
Thanks for your help.

Bob Monroe

**Comment by kstephens** [comment]
Is it possible to build the PiTFT support via DKMS?  Where are the kernel src patches?  I'd rather not run a customized kernel to support a display device.

**Comment by brennen** [comment]
It probably _should_ be, but at the moment this is all kind of (ok, very) ad hoc and we're using [the stuff here](https://github.com/adafruit/Adafruit-Pi-Kernel-o-Matic) to do builds from the source tree [here](https://github.com/adafruit/adafruit-raspberrypi-linux).

**Comment by comp500** [comment]
Untested, but creating the file:

```
Package: *
Pin: origin "http://apt.adafruit.com/raspbian/"
Pin-Priority: -10

```

in `/etc/apt/preferences.d/adafruit`
may decrease the priority of the adafruit repo, therefore making the other kernel priority higher. For some packages, such as node.js, you may have to override this so it is higher priority than debian's repo.

**Comment by jamesy0ung** [comment]
Any new progress? Last post was 21 FEB

**Comment by brennen** [comment]
Closing, as we've deactivated apt.adafruit.com and are no longer maintaining a separate kernel build.
