### ISSUE TITLE
Is it still possible to install the PWM / Servo kernel module?

### ISSUE THREAD

**Issue by robbles** [adafruit/Adafruit-Occidentalis#6]
https://learn.adafruit.com/adafruits-raspberry-pi-lesson-8-using-a-servo-motor/the-pwm-and-servo-kernel-module

Seems to reference an older version of this, which is probably incompatible with the current kernel. Just wondering if it's still possible to install this, hopefully through a package?

**Comment by ladyada** [comment]
hiya you can actually use RPI.GPIO which has PWM built in, 
http://razzpisampler.oreilly.com/ch05.html
which is what we suggest at this time :)

**Comment by robbles** [comment]
Perfect, that's what I had started using already.

Thanks!
