### ISSUE TITLE
occi requires on occidentalis

### ISSUE THREAD

**Issue by misaka** [adafruit/Adafruit-Occidentalis#9]
Hi there,

I just tried running `occi` without installing `occidentalis` and got some errors:

```
run :: handle_selftest :: have package :: occi
dpkg-query: no packages found matching occidentalis
run :: handle_selftest :: 1 :: error :: "dpkg-query" unexpectedly returned exit value 1 at /usr/bin/occi line 275.

Use of uninitialized value $query_result in pattern match (m//) at /usr/bin/occi line 399.
run :: handle_selftest :: no package :: occidentalis
```

But this dependancy isn't expressed in the `occi` package itself where it should be. Also, this means that I have to install `node`, `vim`, `git`, etc to get the `occi` command, and ... nothing against those packages, but I'd rather install those on my terms instead of being forced to pull them in.

**Comment by brennen** [comment]
We've migrated this to a standalone script over in [adafruit/Raspberry-Pi-Installer-Scripts](https://github.com/adafruit/Raspberry-Pi-Installer-Scripts), so no more package.
